//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KonveirEntities1 : DbContext
    {
        public KonveirEntities1()
            : base("name=KonveirEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<develop> develop { get; set; }
        public virtual DbSet<director> director { get; set; }
        public virtual DbSet<Manager1> Manager1 { get; set; }
        public virtual DbSet<master1> master1 { get; set; }
        public virtual DbSet<Zakazchik> Zakazchik { get; set; }
    }
}
